#!/usr/bin/env bun
// Rebuild docs/changelog.md from the public GitHub releases list.
//
// Usage: bun run scripts/generate-docs-changelog.ts
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type GitHubRelease = {
  tag_name: string;
  name: string | null;
  body: string | null;
  draft: boolean;
  prerelease: boolean;
  published_at: string | null;
  html_url: string;
};

const owner = process.env.ARGUS_CHANGELOG_OWNER ?? "Agent-Deployment-Co";
const repo = process.env.ARGUS_CHANGELOG_REPO ?? "argus";
const repoPath = `${owner}/${repo}`;
const root = new URL("..", import.meta.url).pathname;
const outputPath = join(root, "docs/changelog.md");

async function fetchReleases(): Promise<GitHubRelease[]> {
  let url = `https://api.github.com/repos/${repoPath}/releases?per_page=100`;
  const releases: GitHubRelease[] = [];

  while (url) {
    const response = await fetch(url, {
      headers: githubHeaders(),
    });
    if (!response.ok) {
      throw new Error(
        `GitHub releases request failed with ${response.status} ${response.statusText}`,
      );
    }

    releases.push(...((await response.json()) as GitHubRelease[]));
    url = nextLink(response.headers.get("link")) ?? "";
  }

  return releases
    .filter((release) => !release.draft && release.published_at)
    .sort((a, b) => {
      return (
        new Date(b.published_at ?? 0).getTime() -
        new Date(a.published_at ?? 0).getTime()
      );
    });
}

function githubHeaders(): HeadersInit {
  const headers: Record<string, string> = {
    Accept: "application/vnd.github+json",
    "User-Agent": "argus-docs-changelog",
    "X-GitHub-Api-Version": "2022-11-28",
  };
  const token = process.env.GITHUB_TOKEN ?? process.env.GH_TOKEN;
  if (token) {
    headers.Authorization = `Bearer ${token}`;
  }
  return headers;
}

function nextLink(linkHeader: string | null): string | undefined {
  if (!linkHeader) return undefined;
  for (const part of linkHeader.split(",")) {
    const match = part.match(/<([^>]+)>;\s*rel="([^"]+)"/);
    if (match?.[2] === "next") {
      return match[1];
    }
  }
  return undefined;
}

function renderChangelog(releases: GitHubRelease[]): string {
  const lines = [
    "<!-- This file is generated by scripts/generate-docs-changelog.ts. Do not edit by hand. -->",
    "",
    "# Changelog",
    "",
    "Argus publishes release notes on GitHub. This page mirrors every published, non-draft release from newest to oldest.",
    "",
  ];

  if (releases.length === 0) {
    lines.push("No published releases are available yet.", "");
    return lines.join("\n");
  }

  for (const release of releases) {
    lines.push(...renderRelease(release));
  }

  return lines.join("\n");
}

function renderRelease(release: GitHubRelease): string[] {
  const title = escapeText(cleanText(release.name || release.tag_name));
  const published = formatDate(release.published_at);
  const releaseUrl = safeGithubUrl(release.html_url);
  const changes = changeBullets(release.body ?? "");
  const contributors = newContributorBullets(release.body ?? "");
  const compareUrl = fullChangelogUrl(release.body ?? "");
  const lines = [
    `## ${title}`,
    "",
    release.prerelease
      ? `Published ${published} as a prerelease. [Open release](${releaseUrl}).`
      : `Published ${published}. [Open release](${releaseUrl}).`,
    "",
  ];

  if (changes.length > 0) {
    lines.push("### Changes", "", ...changes, "");
  } else {
    lines.push("No release notes were published for this version.", "");
  }

  if (contributors.length > 0) {
    lines.push("### New contributors", "", ...contributors, "");
  }

  if (compareUrl) {
    lines.push(`[Full changelog on GitHub](${compareUrl}).`, "");
  }

  return lines;
}

function changeBullets(body: string): string[] {
  const section = markdownSection(body, "What's Changed");
  return bulletLines(section).map((line) => renderChangeBullet(line));
}

function newContributorBullets(body: string): string[] {
  const section = markdownSection(body, "New Contributors");
  return bulletLines(section).map((line) => renderContributorBullet(line));
}

function markdownSection(body: string, heading: string): string[] {
  const lines = body.replace(/\r\n/g, "\n").split("\n");
  const section: string[] = [];
  let inSection = false;

  for (const line of lines) {
    const headingMatch = line.match(/^##+\s+(.+?)\s*$/);
    if (headingMatch) {
      if (inSection) break;
      inSection = cleanText(headingMatch[1] ?? "").toLowerCase() === heading.toLowerCase();
      continue;
    }
    if (inSection) {
      section.push(line);
    }
  }

  return section;
}

function bulletLines(lines: string[]): string[] {
  return lines
    .map((line) => line.match(/^\s*[*-]\s+(.+?)\s*$/)?.[1])
    .filter((line): line is string => Boolean(line));
}

function renderChangeBullet(line: string): string {
  const pr = line.match(
    /^(.*?)\s+by\s+@[A-Za-z0-9-]+\s+in\s+(https:\/\/github\.com\/[^/]+\/[^/]+\/pull\/(\d+))$/,
  );
  if (!pr) {
    return `- ${escapeText(cleanText(line))}`;
  }

  const title = escapeText(cleanText(pr[1] ?? line));
  const url = safeGithubUrl(pr[2] ?? "");
  const number = escapeText(pr[3] ?? "");
  return `- ${title} ([#${number}](${url}))`;
}

function renderContributorBullet(line: string): string {
  const contribution = line.match(
    /^(@[A-Za-z0-9-]+)\s+made their first contribution in\s+(https:\/\/github\.com\/[^/]+\/[^/]+\/pull\/(\d+))$/,
  );
  if (!contribution) {
    return `- ${escapeText(cleanText(line))}`;
  }

  const user = escapeText(contribution[1] ?? "");
  const url = safeGithubUrl(contribution[2] ?? "");
  const number = escapeText(contribution[3] ?? "");
  return `- ${user} made their first contribution ([#${number}](${url})).`;
}

function fullChangelogUrl(body: string): string | undefined {
  const match = body.match(
    /\*\*Full Changelog\*\*:\s*(https:\/\/github\.com\/[^\s)]+)/i,
  );
  return match?.[1] ? safeGithubUrl(match[1]) : undefined;
}

function formatDate(value: string | null): string {
  if (!value) return "unknown date";
  return new Intl.DateTimeFormat("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  }).format(new Date(value));
}

function safeGithubUrl(url: string): string {
  const githubPrefix = `https://github.com/${repoPath}/`;
  if (url.startsWith(githubPrefix)) {
    return url.replace(/[)>]+$/g, "");
  }
  return `https://github.com/${repoPath}/releases`;
}

function cleanText(value: string): string {
  return value
    .replace(/[–—]/g, "-")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

function escapeText(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\*/g, "\\*")
    .replace(/_/g, "\\_")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]")
    .replace(/#/g, "\\#")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

let releases: GitHubRelease[];
try {
  releases = await fetchReleases();
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  // A transient GitHub API hiccup shouldn't take down an otherwise-fine docs
  // deploy. If a changelog is already committed, keep it and warn; only fail
  // hard when there's nothing to fall back to.
  if (existsSync(outputPath)) {
    console.warn(
      `Could not refresh the changelog from GitHub (${message}). Keeping the existing docs/changelog.md.`,
    );
    process.exit(0);
  }
  throw new Error(
    `Could not fetch releases from GitHub and no docs/changelog.md exists to fall back to: ${message}`,
  );
}
writeFileSync(outputPath, renderChangelog(releases));
console.log(`Wrote ${releases.length} releases to docs/changelog.md`);
